# Generated by Django 3.1.7 on 2021-04-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='app/image'),
            preserve_default=False,
        ),
    ]
