# Generated by Django 3.1.7 on 2021-04-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='timeStamp',
        ),
    ]
