# Generated by Django 3.1.7 on 2021-04-19 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_faq_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 18, 36, 2, 878612)),
        ),
    ]
