# Generated by Django 3.1.7 on 2021-04-22 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_faq_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='slug',
        ),
        migrations.AlterField(
            model_name='faq',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 11, 49, 46, 711948)),
        ),
    ]
