# Generated by Django 3.1.7 on 2021-04-26 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210422_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='devanshi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 26, 16, 29, 55, 608748)),
        ),
    ]
