# Generated by Django 3.1.7 on 2021-04-26 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210426_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 26, 16, 37, 39, 494738)),
        ),
    ]
