# Generated by Django 3.2 on 2021-05-02 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210426_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='faq',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 12, 56, 17, 94707)),
        ),
    ]
